Stricter CheckStyle enforcement of JavaDoc (#89)
* Stricter checkstyle enforcement of JavaDoc

* Mass reformat, fix remaining CS issues

diff --git a/src/test/resources/com/aws/iot/evergreen/kernel/config_broken.yaml b/src/test/resources/com/aws/iot/evergreen/kernel/config_broken.yaml
--- a/src/test/resources/com/aws/iot/evergreen/kernel/config_broken.yaml
+++ b/src/test/resources/com/aws/iot/evergreen/kernel/config_broken.yaml
@@ -1,14 +1,14 @@
 installErrorRetry:
   install: |-
-      sleep 1
-      if [ -f "/tmp/egInstallErrorRetry" ]; then
-        echo "INSTALL_SUCCEED"
-        rm /tmp/egInstallErrorRetry
-      else
-        echo "INSTALL_FAIL"
-        touch /tmp/egInstallErrorRetry
-        exit 1
-      fi
+    sleep 1
+    if [ -f "/tmp/egInstallErrorRetry" ]; then
+      echo "INSTALL_SUCCEED"
+      rm /tmp/egInstallErrorRetry
+    else
+      echo "INSTALL_FAIL"
+      touch /tmp/egInstallErrorRetry
+      exit 1
+    fi
   shutdown:
     rm -f /tmp/egInstallErrorRetry
 
