Fix state transition of 'startup/shutdown' script

diff --git a/src/test/resources/com/aws/iot/evergreen/kernel/config_broken.yaml b/src/test/resources/com/aws/iot/evergreen/kernel/config_broken.yaml
--- a/src/test/resources/com/aws/iot/evergreen/kernel/config_broken.yaml
+++ b/src/test/resources/com/aws/iot/evergreen/kernel/config_broken.yaml
@@ -1,16 +1,14 @@
 installErrorRetry:
   install: |-
-      sleep 1
-      if [ -f "/tmp/egInstallErrorRetry" ]; then
-        echo "INSTALL_SUCCEED"
-        rm /tmp/egInstallErrorRetry
-      else
-        echo "INSTALL_FAIL"
-        touch /tmp/egInstallErrorRetry
-        exit 1
-      fi
-  shutdown:
-    rm -f /tmp/egInstallErrorRetry
+    sleep 1
+    if [ -f "/tmp/egInstallErrorRetry" ]; then
+      echo "INSTALL_SUCCEED"
+      rm /tmp/egInstallErrorRetry
+    else
+      echo "INSTALL_FAIL"
+      touch /tmp/egInstallErrorRetry
+      exit 1
+    fi
 
 runErrorRetry:
   run: |-
@@ -24,16 +22,18 @@ main:
     skipif: true
     all: echo All installed
   requires: installErrorRetry, runErrorRetry
-  setenv:
-    JUSTME: fancy a spot of tea?
-  run: |-
-    echo $PATH
-    pwd
-    printenv
-    echo RUNNING
-    while true; do
-    date; sleep 5;
-    done
+
+  run:
+    setenv:
+      JUSTME: fancy a spot of tea?
+    script: |-
+      echo $PATH
+      pwd
+      printenv
+      echo RUNNING
+      while true; do
+      date; sleep 5;
+      done
   download:
     hw.jar: http://foo/hw.jar
   args: -jar {hw.jar}
