Porting to Windows (#280)
* Shutdown kernel lifecycle after each test

If we don't do that, there is a tlog file being kept open, resulting the temp dir can't be removed, causing test error.

* Declare direct dependency on a newer version of jna

zeroturnaround brings in an older version jna which tries to load msvcr100.dll.
msvcr100.dll is not shipped with recent Windows/VC redist.

* Update maven.yml

* Fix flaky tests on t3a.medium EC2

* Ignore couple exceptions in ExceptionLogProtector
* Ran into NPE in ThreadProtector. Add potential fix
* Test coverage drop to 0.79 on Windows.


* Update maven.yml

* Increase timeout for some flaky tests when running on Windows

* Also sleep a little bit in ThreadProtector if there is some active threads.

* Update maven.yml

* Update maven.yml

* Run e2e only on Linux for now

* Clean up

* Remove lenient = true
* Use Path.compareTo

* * Change more workflows to run on Linux only
* Increase some timeouts to fix flakiness
* Another attempt to fix NPE in ThreadProtector

* Ignore InvalidExitValueException if the process is not alive anymore

* Longer timeout

* longer timeouts

* fix test

* rename code style file for Intellij
Fine adjust coverage limit

* * coverage adjustment
* port new code - need to merge this quick!

* Clean up e2e-test to run on Linux only (revert back to same as master)

Co-authored-by: Francis Fu <fufranci@amazon.com>

diff --git a/src/integrationtests/resources/com/aws/iot/evergreen/integrationtests/kernel/config_startup_error_retry.yaml b/src/integrationtests/resources/com/aws/iot/evergreen/integrationtests/kernel/config_startup_error_retry.yaml
--- a/src/integrationtests/resources/com/aws/iot/evergreen/integrationtests/kernel/config_startup_error_retry.yaml
+++ b/src/integrationtests/resources/com/aws/iot/evergreen/integrationtests/kernel/config_startup_error_retry.yaml
@@ -1,24 +1,41 @@
 services:
   startupErrorRetry:
     lifecycle:
-      startup: |-
-        if [ -f "/tmp/egStartupErrorRetrySucceed" ]; then
-          echo "StartUp_SUCCEED"
-          rm /tmp/egStartupErrorRetrySucceed
-        else
-          echo "StartUp_FAIL"
-          touch /tmp/egStartupErrorRetrySucceed
-          exit 1
-        fi
+      posix:
+        startup: |-
+          if [ -f "/tmp/egStartupErrorRetrySucceed" ]; then
+            echo "StartUp_SUCCEED"
+            rm /tmp/egStartupErrorRetrySucceed
+          else
+            echo "StartUp_FAIL"
+            touch /tmp/egStartupErrorRetrySucceed
+            exit 1
+          fi
+      windows:
+        # DO NOT ADD INDENTATION BELOW
+        # Adding "helpful" indentation breaks the way yaml parses the string
+        startup: >-
+          powershell -command "& {if ([System.IO.File]::Exists(\"egStartupErrorRetrySucceed\")) {
+          echo StartUp_SUCCEED;
+          Remove-Item egStartupErrorRetrySucceed;
+          } else {
+          echo StartUp_FAIL;
+          New-Item egStartupErrorRetrySucceed;
+          exit 1;
+          }}"
 
   main:
     lifecycle:
       install:
         all: echo All installed
-      run: |-
-        echo main of config_startup_error_retry is running
-        while true; do
-        date; sleep 5;
-        done
+      posix:
+        run: |-
+          echo main of config_startup_error_retry is running
+          while true; do
+          date; sleep 5;
+          done
+      windows:
+        run: |-
+          powershell -command "& { echo \"main of config_startup_error_retry is running\"; while (1) { sleep 5 }}"
     dependencies:
       - startupErrorRetry
