Fix more tests

diff --git a/src/integrationtests/resources/com/aws/iot/evergreen/integrationtests/kernel/config_install_error.yaml b/src/integrationtests/resources/com/aws/iot/evergreen/integrationtests/kernel/config_install_error.yaml
--- a/src/integrationtests/resources/com/aws/iot/evergreen/integrationtests/kernel/config_install_error.yaml
+++ b/src/integrationtests/resources/com/aws/iot/evergreen/integrationtests/kernel/config_install_error.yaml
@@ -1,18 +1,26 @@
 services:
   installerror:
     lifecycle:
-      install: |-
-        echo "INSTALL_ERROR"
-        exit 1
+      posix:
+        install: |-
+          echo "INSTALL_ERROR"
+          exit 1
+      windows:
+        install: |-
+          powershell -command echo INSTALL_ERROR; exit 1
 
   main:
     lifecycle:
       install:
         all: echo All installed
-      run: |-
-        echo main of config_install_error is running
-        while true; do
-        date; sleep 5;
-        done
+      posix:
+        run: |-
+          echo main of config_install_error is running
+          while true; do
+          date; sleep 5;
+          done
+      windows:
+        run: >-
+          powershell -command "& { echo \"main of config_install_error is running\"; while (1) { sleep 5 } }"
     dependencies:
       - installerror
